package com.facultytimetable.pro.presentation.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val SETUP_WIZARD = "setup/wizard"
    const val DASHBOARD = "dashboard"
    const val FACULTY_LIST = "faculty/list"
    const val FACULTY_DETAIL = "faculty/detail/{facultyId}"
    const val FACULTY_FORM = "faculty/form?facultyId={facultyId}"
    const val DEPARTMENT_LIST = "department/list"
    const val DEPARTMENT_FORM = "department/form?departmentId={departmentId}"
    const val SUBJECT_LIST = "subject/list"
    const val SUBJECT_FORM = "subject/form?subjectId={subjectId}"
    const val ROOM_LIST = "room/list"
    const val ROOM_FORM = "room/form?roomId={roomId}"
    const val SECTION_LIST = "section/list"
    const val SECTION_FORM = "section/form?sectionId={sectionId}"
    const val SEMESTER_LIST = "semester/list"
    const val SEMESTER_FORM = "semester/form?semesterId={semesterId}"
    const val ACADEMIC_YEAR_LIST = "academic_year/list"
    const val ACADEMIC_YEAR_FORM = "academic_year/form?yearId={yearId}"
    const val TIME_SLOT_CONFIG = "timeslot/config"
    const val HOLIDAY_LIST = "holiday/list"
    const val HOLIDAY_FORM = "holiday/form?holidayId={holidayId}"
    const val FACULTY_LEAVE = "faculty/leave"
    const val FACULTY_LEAVE_FORM = "faculty/leave/form?facultyId={facultyId}&leaveId={leaveId}"
    const val TIMETABLE_GRID = "timetable/grid"
    const val TIMETABLE_DAILY = "timetable/daily/{day}"
    const val TIMETABLE_FACULTY = "timetable/faculty/{facultyId}"
    const val TIMETABLE_DEPARTMENT = "timetable/department/{departmentId}"
    const val TIMETABLE_ROOM = "timetable/room/{roomId}"
    const val TIMETABLE_SECTION = "timetable/section/{sectionId}"
    const val TIMETABLE_GENERATOR = "timetable/generator"
    const val SEARCH = "search"
    const val REPORTS = "reports"
    const val REPORT_DETAIL = "reports/{reportType}"
    const val BACKUP = "backup"
    const val SETTINGS = "settings"
    const val APP_LOCK = "security/lock"
    const val LAB_LIST = "lab/list"
    const val LAB_FORM = "lab/form?labId={labId}"
    const val FACULTY_ASSIGNMENT = "faculty/assignment"
    const val WORKING_DAY = "workingday/config"
    const val RECYCLE_BIN = "recycle/bin"

    fun facultyDetail(id: Long) = "faculty/detail/$id"
    fun facultyForm(id: Long? = null) = if (id != null) "faculty/form?facultyId=$id" else "faculty/form"
    fun departmentForm(id: Long? = null) = if (id != null) "department/form?departmentId=$id" else "department/form"
    fun subjectForm(id: Long? = null) = if (id != null) "subject/form?subjectId=$id" else "subject/form"
    fun roomForm(id: Long? = null) = if (id != null) "room/form?roomId=$id" else "room/form"
    fun sectionForm(id: Long? = null) = if (id != null) "section/form?sectionId=$id" else "section/form"
    fun semesterForm(id: Long? = null) = if (id != null) "semester/form?semesterId=$id" else "semester/form"
    fun academicYearForm(id: Long? = null) = if (id != null) "academic_year/form?yearId=$id" else "academic_year/form"
    fun holidayForm(id: Long? = null) = if (id != null) "holiday/form?holidayId=$id" else "holiday/form"
    fun labForm(id: Long? = null) = if (id != null) "lab/form?labId=$id" else "lab/form"
    fun timetableDaily(day: Int) = "timetable/daily/$day"
    fun timetableFaculty(id: Long) = "timetable/faculty/$id"
    fun timetableDepartment(id: Long) = "timetable/department/$id"
    fun timetableRoom(id: Long) = "timetable/room/$id"
    fun timetableSection(id: Long) = "timetable/section/$id"
    fun facultyLeave(id: Long) = "faculty/leave"
    fun facultyLeaveForm(facultyId: Long, leaveId: Long? = null) =
        if (leaveId != null) "faculty/leave/form?facultyId=$facultyId&leaveId=$leaveId"
        else "faculty/leave/form?facultyId=$facultyId"
    fun reportDetail(type: String) = "reports/$type"
}
